import time
import requests
import io
from VIPMUSIC import app
from config import BANNED_USERS
from pyrogram.enums import ChatAction, ParseMode
from pyrogram import filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton

# API URLs
CHAT_API_URL = "https://chatgpt.apinepdev.workers.dev/?question="
IMAGE_API_URL = "https://pollinations.ai/p/"

# 1. --- CHATGPT COMMAND (Aapka Purana Code) ---
@app.on_message(filters.command(["chatgpt", "ai", "ask", "gpt", "solve"], prefixes=["+", ".", "/", "-", "", "$", "#", "&"]) & ~BANNED_USERS)
async def chat_gpt(bot, message):
    try:
        await bot.send_chat_action(message.chat.id, ChatAction.TYPING)

        if len(message.command) < 2:
            return await message.reply_text(
                "Example:\n\n`/chatgpt Where is the Taj Mahal?`",
                parse_mode=ParseMode.MARKDOWN
            )

        question = message.text.split(' ', 1)[1]
        response = requests.get(f"{CHAT_API_URL}{question}")

        if response.status_code == 200:
            json_data = response.json()

            if "answer" in json_data:
                answer = json_data["answer"]

                # Aapka purana filtering logic
                unwanted_phrases = [
                    "🔗 Join our community",
                    "t.me/",
                    "Answered by",
                    "Join our Telegram"
                ]
                for phrase in unwanted_phrases:
                    if phrase.lower() in answer.lower():
                        answer = answer.split(phrase)[0].strip()

                buttons = InlineKeyboardMarkup(
                    [[InlineKeyboardButton("✙ ʌᴅᴅ ϻє ɪη ʏσυʀ ɢʀσυᴘ ✙", url=f"https://t.me/{app.username}?startgroup=true")]]
                )

                return await message.reply_text(
                    f"**🤖 𝐘ᴏᴜʀ ᴀɴsᴡᴇʀ :**\n\n{answer}",
                    parse_mode=ParseMode.MARKDOWN,
                    reply_markup=buttons
                )
            else:
                return await message.reply_text("⚠️ No valid answer found.")
        else:
            return await message.reply_text(f"⚠️ API Error: {response.status_code}")

    except Exception as e:
        return await message.reply_text(f"⚠️ **Error:** `{str(e)}`", parse_mode=ParseMode.MARKDOWN)


# 2. --- PHOTO GENERATION COMMAND (Naya Feature) ---
@app.on_message(filters.command(["generate", "draw", "photo", "imagine", "aiart"], prefixes=["+", ".", "/", "-", "", "$", "#", "&"]) & ~BANNED_USERS)
async def generate_image(bot, message):
    try:
        if len(message.command) < 2:
            return await message.reply_text(
                "**Kya banau?**\nExample: `/generate a red car on a dark blue road`"
            )

        prompt = message.text.split(None, 1)[1]
        m = await message.reply_text("🎨 **Wait... I am drawing your imagination...**")
        
        await bot.send_chat_action(message.chat.id, ChatAction.UPLOAD_PHOTO)

        # Image generation logic
        encoded_prompt = prompt.replace(" ", "%20")
        gen_url = f"{IMAGE_API_URL}{encoded_prompt}?width=1024&height=1024&model=flux"
        
        # Image download kar ke bhejna taaki error na aaye
        img_res = requests.get(gen_url)
        if img_res.status_code == 200:
            photo = io.BytesIO(img_res.content)
            photo.name = "ai_image.jpg"
            
            await message.reply_photo(
                photo=photo,
                caption=f"**✨ Prompt:** `{prompt}`\n**🤖 Generated by:** @{app.username}",
                reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("✙ ʌᴅᴅ ϻє ɪη ʏσυʀ ɢʀσυᴘ ✙", url=f"https://t.me/{app.username}?startgroup=true")]])
            )
            await m.delete()
        else:
            await m.edit("❌ Failed to generate image. Try again later.")

    except Exception as e:
        await message.reply_text(f"⚠️ **Error:** `{str(e)}`")


__MODULE__ = "Aɪ-Bᴏᴛ"
__HELP__ = """
**Chatting Commands:**
/ai, /chatgpt, /ask - Ask anything from AI.

**Image Commands:**
/generate, /draw, /photo - Generate AI images with any color or style.
Example: `/generate a beautiful girl in red dress`
"""
