import time
import requests
from VIPMUSIC import app
from config import BANNED_USERS
from pyrogram.enums import ChatAction, ParseMode
from pyrogram import filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton, InputMediaPhoto

# API URLs
CHAT_API_URL = "https://chatgpt.apinepdev.workers.dev/?question="
IMAGE_API_URL = "https://pollinations.ai/p/" # Best for high quality images

# --- CHATGPT COMMAND ---
@app.on_message(filters.command(["chatgpt", "ai", "ask", "gpt", "solve"], prefixes=["+", ".", "/", "-", "", "$", "#", "&"]) & ~BANNED_USERS)
async def chat_gpt(bot, message):
    try:
        await bot.send_chat_action(message.chat.id, ChatAction.TYPING)

        if len(message.command) < 2:
            return await message.reply_text(
                "**Usage:**\n`/chatgpt Where is the Taj Mahal?`",
                parse_mode=ParseMode.MARKDOWN
            )

        question = message.text.split(' ', 1)[1]
        response = requests.get(f"{CHAT_API_URL}{question}")

        if response.status_code == 200:
            json_data = response.json()
            if "answer" in json_data:
                answer = json_data["answer"]
                
                # Cleaning unwanted links/ads
                unwanted_phrases = ["🔗 Join our community", "t.me/", "Answered by", "Join our Telegram"]
                for phrase in unwanted_phrases:
                    if phrase.lower() in answer.lower():
                        answer = answer.split(phrase)[0].strip()

                buttons = InlineKeyboardMarkup([[InlineKeyboardButton("✙ ʌᴅᴅ ϻє ɪη ʏσυʀ ɢʀσυᴘ ✙", url=f"https://t.me/{app.username}?startgroup=true")]])

                return await message.reply_text(
                    f"**🤖 𝐀ɪ 𝐑ᴇsᴘᴏɴsᴇ :**\n\n{answer}",
                    parse_mode=ParseMode.MARKDOWN,
                    reply_markup=buttons
                )
        await message.reply_text("⚠️ API error or no response.")
    except Exception as e:
        await message.reply_text(f"⚠️ **Error:** `{str(e)}`")

# --- IMAGE GENERATION COMMAND ---
@app.on_message(filters.command(["generate", "draw", "imagine", "photo", "art"], prefixes=["+", ".", "/", "-", "", "$", "#", "&"]) & ~BANNED_USERS)
async def generate_image(bot, message):
    try:
        if len(message.command) < 2:
            return await message.reply_text(
                "**Usage:**\n`/generate a blue lion in space` \n(Aap color aur style specify kar sakte hain)"
            )

        prompt = message.text.split(None, 1)[1]
        wait_msg = await message.reply_text("🎨 **Wait... Generating your imagination...**")
        
        await bot.send_chat_action(message.chat.id, ChatAction.UPLOAD_PHOTO)

        # Pollinations API handles colors and descriptions automatically in the URL
        # We encode spaces to %20 for the URL
        image_url = f"{IMAGE_API_URL}{prompt.replace(' ', '%20')}?width=1080&height=1080&seed=42&model=flux"

        # Sending the photo
        await message.reply_photo(
            photo=image_url,
            caption=f"**✨ Prompt:** {prompt}\n\n**Generated by:** @{app.username}",
            reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("✙ ʌᴅᴅ ϻє ɪη ʏσυʀ ɢʀσυᴘ ✙", url=f"https://t.me/{app.username}?startgroup=true")]])
        )
        await wait_msg.delete()

    except Exception as e:
        await message.reply_text(f"❌ **Failed to generate image.**\n`{str(e)}`")

__MODULE__ = "Aɪ-Cʜᴀᴛ"
__HELP__ = """
**AI & ChatGPT Commands:**
/ai [ǫᴜᴇʀʏ] - ᴀsᴋ ʏᴏᴜʀ ǫᴜᴇsᴛɪᴏɴ ᴡɪᴛʜ ᴄʜᴀᴛɢᴘᴛ
/ask [ǫᴜᴇʀʏ] - ᴀsᴋ ᴀɴʏᴛʜɪɴɢ ᴛᴏ ᴛʜᴇ ʙᴏᴛ

**Photo Generation Commands:**
/generate [ᴘʀᴏᴍᴘᴛ] - ᴄʀᴇᴀᴛᴇ AI ɪᴍᴀɢᴇs (ᴇ.ɢ. /generate red car in rain)
/draw [ᴘʀᴏᴍᴘᴛ] - ᴅʀᴀᴡ ʏᴏᴜʀ ɪᴍᴀɢɪɴᴀᴛɪᴏɴ ɪɴ ᴅɪғғᴇʀᴇɴᴛ ᴄᴏʟᴏʀs
/imagine [ᴘʀᴏᴍᴘᴛ] - ʜɪɢʜ ǫᴜᴀʟɪᴛʏ AI ᴀʀᴛ ɢᴇɴᴇʀᴀᴛᴏʀ
"""
